### ISSUE TITLE
Convert onKeyPress

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/ts-converter#1]
Usally as user I simply copy/paste values inside editbox and press return to see conversion.
Right now this seems to be not possible, could you please add it ?

**Comment by mirkoperillo** [comment]
Thank you for your suggestion @albertotn .

I think I will add this feature in the next release

**Comment by albertotn** [comment]
If possible ( if ! ) you should also add on focus when user click on extension button, so it's more easy to paste/convert
